---
templates:
  rclone:
    condition: ck8sManagementCluster.enabled
    chart: charts/rclone
    version: 0.1.0
    namespace: rclone
    labels:
      app: rclone
    needs:
      - kube-system/admin-namespaces

  rclone-restore:
    inherit: [ template: rclone ]
    installed: {{ .Values | get "objectStorage.restore.enabled" false }}
    name: rclone-restore
    values:
      - values/rclone/restore.yaml.gotmpl

  rclone-sync:
    inherit: [ template: rclone ]
    installed: {{ and (.Values | get "objectStorage.restore.enabled" false | not) (.Values | get "objectStorage.sync.enabled" false) }}
    name: rclone-sync
    values:
      - values/rclone/sync.yaml.gotmpl
