helmDefaults:
  timeout: 600
  createNamespace: false
  skipDeps: true

environments:
  workload_cluster:
    values:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/wc-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/wc-config.yaml"
    secrets:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml"
  service_cluster:
    values:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/sc-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/sc-config.yaml"
    secrets:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml"
---

releases:

- name: common-np
  namespace: kube-system
  labels:
    app: common-np
  chart: ./charts/networkpolicy/common
  version: 0.1.0
  values:
  - values/networkpolicy/common.yaml.gotmpl

{{ if eq .Environment.Name "service_cluster" }}

- name: service-cluster-np
  namespace: kube-system
  labels:
    app: service-cluster-np
  chart: ./charts/networkpolicy/service-cluster
  version: 0.1.0
  values:
  - values/networkpolicy/service-cluster.yaml.gotmpl

{{ end }}

{{ if eq .Environment.Name "workload_cluster" }}

- name: workload-cluster-np
  namespace: kube-system
  labels:
    app: workload-cluster-np
  chart: ./charts/networkpolicy/workload-cluster
  version: 0.1.0
  values:
  - values/networkpolicy/workload-cluster.yaml.gotmpl

{{ end }}
