bases:
  - ./bases/environment.yaml
  - ./bases/upstream.yaml
---

releases:

- name: kube-prometheus-stack
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
  inherit: [ template: kube-prometheus-stack ]
  # https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
  # The --dry-run flag of helm install and helm upgrade is not currently supported for CRDs.
  disableValidationOnInstall: true
  values:
{{ if eq .Environment.Name "service_cluster" }}
  - values/kube-prometheus-stack-sc.yaml.gotmpl
{{ end }}
{{ if eq .Environment.Name "workload_cluster" }}
  - values/kube-prometheus-stack-wc.yaml.gotmpl
{{ end }}

- name: kube-state-metrics-extra-resource-metrics
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
  chart: ./charts/kube-state-metrics-extra-resource-metrics
  version: 0.1.0
  installed: {{ .Values.kubeStateMetrics.clusterAPIMetrics.enabled }}
  values:
  - values/kube-state-metrics-extra-resource-metrics.yaml.gotmpl

- name: thanos-ingress-secret
{{- if eq .Environment.Name "service_cluster" }}
  namespace: thanos
{{- else if eq .Environment.Name "workload_cluster" }}
  namespace: monitoring
{{- end }}
  labels:
    app: thanos
  chart: ./charts/thanos/ingress-secret
  version: 0.1.0
  installed: {{ .Values.thanos.enabled }}
  values:
  - values/thanos/ingress-secret.yaml.gotmpl
