helmDefaults:
  timeout: 600
  createNamespace: false
  skipDeps: true

environments:
  workload_cluster:
    values:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/wc-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/wc-config.yaml"
    secrets:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml"
  service_cluster:
    values:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/sc-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/sc-config.yaml"
    secrets:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml"
---

releases:
- name: gatekeeper
  namespace: gatekeeper-system
  labels:
    app: gatekeeper
    component: gatekeeper
  chart: ./upstream/gatekeeper
  version: 3.11.0
  installed: {{ .Values.opa.enabled }}
  disableValidationOnInstall: true
  wait: true
  values:
  - values/gatekeeper/gatekeeper.yaml.gotmpl
