bases:
  - ./bases/environment.yaml
  - ./bases/upstream.yaml
---

releases:
- name: gatekeeper
  namespace: gatekeeper-system
  labels:
    app: gatekeeper
    component: gatekeeper
  inherit: [ template: gatekeeper ]
  disableValidationOnInstall: true
  wait: true
  values:
  - values/gatekeeper/gatekeeper.yaml.gotmpl
