bases:
  - ./bases/environment.yaml
  - ./bases/upstream.yaml
---

releases:
- name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
  inherit: [ template: cert-manager ]
  # https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
  # The --dry-run flag of helm install and helm upgrade is not currently supported for CRDs.
  disableValidationOnInstall: true
  wait: true
  values:
  - values/cert-manager.yaml.gotmpl
