helmDefaults:
  timeout: 600
  createNamespace: false
  skipDeps: true

environments:
  workload_cluster:
    values:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/wc-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/wc-config.yaml"
    secrets:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml"
  service_cluster:
    values:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/defaults/sc-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/common-config.yaml"
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/sc-config.yaml"
    secrets:
      - "{{ requiredEnv "CK8S_CONFIG_PATH" }}/secrets.yaml"
---

releases:
- name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
  chart: ./upstream/cert-manager
  version: v1.11.0
  # https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations
  # The --dry-run flag of helm install and helm upgrade is not currently supported for CRDs.
  disableValidationOnInstall: true
  wait: true
  values:
  - values/cert-manager.yaml.gotmpl
