clouds:
  openstack:
    auth:
      auth_url: https://v2.dashboard.sto1.safedc.net:5000/v3/
      username: "haorui.peng@elastisys.com"
      project_name: "dev.elastisys.se"
      project_id: 001143c94c2342e8adf997239767ff5f
      user_domain_name: "users"
      password: "suitsradarnileAromaminedkirk"
    region_name: "sto1"
    interface: "public"
    identity_api_version: 3
