objectStorage: {}
grafana:
    password: ENC[AES256_GCM,data:HP+fAD5yf2xl++GmvDe/andzu1g=,iv:NZKA8hHSCO6+2PAp6jo6xz9RzJZhy6i3P6qeg89StDc=,tag:dNAZp3+UXIFibmzijapAIQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:7CtiIp1qETeAwAxf3/DInrSdg7k=,iv:mF/F2mWoeC0KTvgpX+6ZOSdbI1I0HuoMyjJVS76OKLM=,tag:rRofgiqiAHcVxq6NlGAYhw==,type:str]
    opsClientSecret: ENC[AES256_GCM,data:c+KGEIQcwidHHCqAPiv2i+1xKlU=,iv:iVxv2z+Ya6niBVlIvbpBGc/1qwwdVhUyFu6Y3i/ZR+c=,tag:DgP82GSPbCnX476NTM8M3w==,type:str]
    ops:
        envRenderSecret: []
    user:
        envRenderSecret: []
harbor:
    password: ENC[AES256_GCM,data:6Rb6dWu06tvOR2w09Y/tQXjPCvM=,iv:felOyZcOLDs8hbWqPAt1/B27kifSq2FGaFy4yO+eJoQ=,tag:iTa1kfkwy86+k1OeKtyowA==,type:str]
    clientSecret: ENC[AES256_GCM,data:nW79tLkS4a4wl25QRK/XqJ7swD4=,iv:O6S8qTCsDZfPWsx9rs4oO0UYcw7T3+AGQAIWdn6KxP8=,tag:Y5XjyQ79UmISIOdB152QIA==,type:str]
    xsrf: ENC[AES256_GCM,data:OFmkgaOgJHyXZFWQbcIqCWTowwZtm/tLYfTtkqO87mM=,iv:VEpNMBUlSWxcU+bjX00uXSfIxlnGu6C3ITNs+VejzKw=,tag:VSJPHIClXjvJEW5Tn883tw==,type:str]
    coreSecret: ENC[AES256_GCM,data:vNQZSXCY8xLAXId/WCnTIuq/7A4=,iv:3Ohk7q4XRBtyWTnT058mD4YRp4AZlaUFoAjBkBWGxi8=,tag:dBz/kF6IyWnb2QPow9Nwlw==,type:str]
    jobserviceSecret: ENC[AES256_GCM,data:/bFL4HsGXv//08GITEphYe0f3iU=,iv:lkuP1R5G4/NcgfO6xI1UFBhc3fY8m2fiGsRCsElFFUs=,tag:fOHu0Jq3JgwZKI4gSBGsdw==,type:str]
    registrySecret: ENC[AES256_GCM,data:ECwa0AYDSNCNJdlmP7Qw6LdA6/M=,iv:rdRSnq4dXrcNwZehvWSTP8l8dRcH5bsFKwjxRye0lpk=,tag:V92jMHbIq3BY8KKBYxn2jQ==,type:str]
    internal:
        databasePassword: ENC[AES256_GCM,data:Q7OIeIo1TwvaazEsldHIHiiFmeM=,iv:oFtBaG3zZw2/efTHDr9wlnEiiNsdM8qosBSTT2NYwzE=,tag:x9qm3gQ9mqtRgoV4+VrWmg==,type:str]
    registryPassword: ENC[AES256_GCM,data:JWAmLerpJc8ZhKysG3/Ccqk6feM=,iv:tYL+nWsMZ5XVsM1JWekW1LmSNl888dvlK+8WIRh6BVo=,tag:9V3pey/shhsNlh1DoYuu7Q==,type:str]
    registryPasswordHtpasswd: ENC[AES256_GCM,data:+txFtAIdoidHUG0eA+o40bzXluSPnr0TCISqfdnCTazIFKMcuKdrPlF6npKzycA3W6VVd/bIc4aNH00UT3Ku73r3V3umMUyAVi9er3LMCAOf,iv:nRFHrzEn0uLcVJkd9le3v+Suh2MOylTLJcO+o8btjAE=,tag:dRPwQF2hWdL9QhY9Zy6qiw==,type:str]
thanos:
    receiver:
        basic_auth:
            password: ENC[AES256_GCM,data:1KFPvx9ECbR/E55TVjtNBssyDbs=,iv:+Zx1jQbXfDZHSXKaTSxWxGcecUikqzWB8OohnCP5m6o=,tag:sRFqzr+a84snmYy7p9c9Gg==,type:str]
            passwordHash: ENC[AES256_GCM,data:qfLxtH65C9MckGicveM7PaTQ3EBFHRK357+1YxgtklnOcnm/xw==,iv:o15/ZttnfXwknIN0Cfye3CysG3xfIdMRNAUD/Vjz4Qw=,tag:UYqwfVBVEyXmehC2BE+ScA==,type:str]
opensearch:
    adminPassword: ENC[AES256_GCM,data:zO9STnM927J6sE32oLcabxB77y0=,iv:RO559PyVLqaj9VHQXRazj7AX5yXF4HMuC/sYx0Af6Mo=,tag:dyXoQEy5mN+q58N7nwDXlQ==,type:str]
    adminHash: ENC[AES256_GCM,data:gj9R7IGD/o+cSfWl/L3FSak7iYBqku/2Ek9JUzw4P2gPQy3FYKxR+sDo7aZ/0ZeuSKnAL8NAfVTnZB+K,iv:7MeGNJ3cnG0B4W4X8gVmb6TvDyBrKwQoODEpgy/ZekM=,tag:dvyuhSTHg3TF8AhXJEzuLw==,type:str]
    clientSecret: ENC[AES256_GCM,data:/A8ROuzcgcCNo0LYvxMRMAeTNpQ=,iv:P/HjbIioRIa5YRdqBs7hAn8z/WXseV5vk+N7goVdswg=,tag:fDar1VtiWJ+Pu0CcYlM7wg==,type:str]
    configurerPassword: ENC[AES256_GCM,data:kiPN+IHJnFQdV3lozJpPAqZJIyo=,iv:ZVsfO2ZCRRUx/akytLXXWlRwk7P9IP5WOBb+mlXxvGQ=,tag:glqUEtm+2r9OifBiqlqLgg==,type:str]
    configurerHash: ENC[AES256_GCM,data:8mVpQuyD0/3VPQSUR5c7LtyGJRdCi+Nqn0EPb1D89Zu8uYRQxZeAToVJUI8lIUmYEiG+a6IZUecKcoRw,iv:XSCRuj3sLwglpG6zslgpriiLp1ZS6v8j7gZa/9yYuzw=,tag:jEn0gC+ittEVq0uaNjIm6w==,type:str]
    dashboardsPassword: ENC[AES256_GCM,data:zXGbb+h9rX69Ngl7QKI2S6DA44E=,iv:wL8Z/7GXKKKxjSbjp1pYwhZ/oogLq3XesxREEGJn0JU=,tag:33e9+Bo4+twgU+isCBitMA==,type:str]
    dashboardsHash: ENC[AES256_GCM,data:8/8N33HuQneq+erxcJizEbA2X7rDH1bmZ2K0q5UrSrrySMG+5eMhpCLtHrHhuWGFx8jdFWK1olxsIXZU,iv:WN9880FZJoEaY5Drdtwei2WBGaly6qcYRSUPkFkcbYQ=,tag:+eZuRNzg9Ztu7Q5YOIyWjA==,type:str]
    dashboardsCookieEncKey: ENC[AES256_GCM,data:tvrLuVu7heNkG+DK+8SxT4kkOxFm3OlLWKGT5yIL/Lc=,iv:Vg23sHZg67tCTtNWUQWMJEoF5ZlS6vY64Yvarwa8cPw=,tag:19CIEtr7Fl13CvG0gDQ2cA==,type:str]
    fluentdPassword: ENC[AES256_GCM,data:Cxwk5PWis+NJVRiRE3tl0zS4o7s=,iv:nPAgoSqNgHooVUbqFz5CVcYdcdr/qJ2n7Q8UjtNpwrE=,tag:7cPubL0hxThi5mGvpfK3hA==,type:str]
    curatorPassword: ENC[AES256_GCM,data:ntKY9hHzoL4rcZisYdB5QNw63jo=,iv:k/lP4TO0SsLzBWyFz89w7ecJU3EGWHydznYV50bMu48=,tag:/Bf3sdPcouKBDNj7N6eILQ==,type:str]
    snapshotterPassword: ENC[AES256_GCM,data:YX5t9Cuszo3R+uzIebWlA+ENoMc=,iv:0lCVzc280yf/pXtP/YC4On3VYjivxQ9Cgleann68onY=,tag:ZaxPDFELD+laXk3DgUBiMA==,type:str]
    metricsExporterPassword: ENC[AES256_GCM,data:Cvk/VbFKo9OQj5FyX9rQN9jKigc=,iv:WLsfi3NCwLV0V1S6B1bf/jByFmCET57nNx39RnXfF3s=,tag:w1VRsYJPoIyZUqdwkxCs5g==,type:str]
    extraUsers: []
kubeapiMetricsPassword: ENC[AES256_GCM,data:OCtvsXRPPevEveNTXGnp/r0+Yac=,iv:422j6Wmuc46fNwmxIS8lNkJqXr2klvfSVcN04RH9fGc=,tag:LlClfdmA8oEtTkivHCCmQQ==,type:str]
alerts:
    slack:
        apiUrl: ENC[AES256_GCM,data:hoDvF9nEc8uqGtmEWQs=,iv:vVuRlcVJEQgGb75KXr2Gz8eEJlBFkGGbJL0NYZxet+w=,tag:cHtfAeelZd8bHv5A51e6OQ==,type:str]
    opsGenie:
        apiKey: ENC[AES256_GCM,data:4QykzsPo,iv:Bkwt34T9veCXp+JZN+9DBuM9jcxTvpFUjEiRpA43nTo=,tag:2ZWZDhLNqYbBvsvKp2Dsow==,type:str]
kured:
    slack:
        botToken: ""
dex:
    staticPassword: ENC[AES256_GCM,data:n/4MhV+jUhixd6mjuwUtsMbP97/DY5wCGOnqUm4+nHkPIelYgRL4lx8eECc2/lyqPLgnGfU157lI4kFM,iv:Fzk+px6puvEvKmaRihEAh2XkkHtbgiToL6Ip+JGhQos=,tag:BeztzgC9klGxCgVYJ8g5sQ==,type:str]
    kubeloginClientSecret: ENC[AES256_GCM,data:DmJzn3xaCGEsIuFBExRdgoZX9U4=,iv:Ws0XSS4Sdwop7K8+i5acz3QEN+cmW8doq9CkiOOoK/A=,tag:+1SC692m8C1PqW39oAm0qQ==,type:str]
    connectors:
        - name: ENC[AES256_GCM,data:O0BxC10PbAU1,iv:FRa1AZA9z+Oj29mtLQMWEsrpBHtkQndPulc4ijePWq4=,tag:F2kZ6ddhBdoo3/nb8Yy4Ng==,type:str]
          id: ENC[AES256_GCM,data:vhyEwzQm9MNJ7PiP2SffMg==,iv:aZpefMMS/UXpG9UACcDu94FmI4wrBaGQBK2FQMIPEaM=,tag:ks2JLXQ+B8SzJAQkQeaI9Q==,type:str]
          type: ENC[AES256_GCM,data:ayRVeBHH,iv:xsN0iYAKM99sC8diDH3juMJ8UviatUSn/Q3kiF6VvaE=,tag:oi2O1QPeGj7WzDDrYh8reQ==,type:str]
          config:
            clientID: ENC[AES256_GCM,data:JiJ+68CQFDvO3ElVRdUnlKz2yA8hWCfyMSKSqXLtyBcJ3ffz8mFWbTPwVRLT6JI5Uf2cJI/3nkxUhoYaGwCn9hFyGOy0D7X/,iv:CYLKLGeLV11XEWfdvk5/krZU6uNQjdk3xfSpdKM4/Ts=,tag:Ms/CG2PdDpM5XjG0No4Ztw==,type:str]
            #ENC[AES256_GCM,data:JBiAxXjJ01EiKjs5y3s6+vU=,iv:cczLhhBpCyJJjdPPEyOTKFYtczFTRiLN+sI9H83GHIo=,tag:kJevhC6CuQMoPDN3f+aOuw==,type:comment]
            clientSecret: ENC[AES256_GCM,data:S8iCQuLz7bjss6Mh5v+bXXcQDlXagInMULd/IwuO9P+3RKA=,iv:N+G4vKHAeJ1clLZQiDTsqvC95bU3VsZyl2bQP2IeDb4=,tag:L4mN0p17KiXBdpMY61AFFA==,type:str]
            #ENC[AES256_GCM,data:qu7ZtPdtWC8Mw8dj802TwCyuRfUy,iv:mWzxfop8eUUHqgWNz7R6dXTpsTXlr+2A3oPPuXjWXog=,tag:UnG865ZK8MKklm1E2P4YCw==,type:comment]
            redirectURI: ENC[AES256_GCM,data:Rciw6fNISSn01Zpvb/RuK+nbNQGOvR97By9QgfPtcDwoqS+dk7cndnuxOFI5rrBOke3sdxI=,iv:JaPTvRJltVJC0/rBLvoaoTeNbZbY32R+FcmUlnfnuIQ=,tag:bQrg6owD20xlRtDai5YAqg==,type:str]
            #ENC[AES256_GCM,data:Dqb0TG7czDlmT3niks/wERJbVAeJQcX39g==,iv:YZ4EC0/LYXgmhNH4E9NqpwyHpzIMaWt0oKemrHKEOIU=,tag:3VGnmgrxqOvh3uxTgSqltw==,type:comment]
            serviceAccountFilePath: ENC[AES256_GCM,data:mcI8I3JshkYbK0cn9iruIwMuH9eERbk=,iv:hCGQbMnvMBk2amalhDzWMSrUihiahM/QUTbIdH2r57g=,tag:mo41C4DsXsicnTBRWsRA7A==,type:str]
            adminEmail: ENC[AES256_GCM,data:Jsl8NEPkAFp9gL4zzlWm7/hyNEaoXvVHHGp3wBoC3g==,iv:TSvoUqT60cgXBrfD9rBAEBOisssRk7u3meXzfONTjWs=,tag:7zTbCtesgcQYrXeguqOqLg==,type:str]
            groups:
                - ENC[AES256_GCM,data:W08OOG69EWe/xKetxAgXS0hlZaOE67ff,iv:xYFSq+it1OC0UACs5CrmmrKRCtgrSiwxQuPsBpCvN9g=,tag:SxAAW9zeLaSSrAyIcB3I9A==,type:str]
            #ENC[AES256_GCM,data:kmHGfUw4EMgX217nVikdKA==,iv:jVYPccOa7oz8BqiAnAV+t/Png4eK0etASMPDlYBD/WM=,tag:Ba8KT4M4XiU99XHuKRUhGg==,type:comment]
            hostedDomains:
                - ENC[AES256_GCM,data:o1ZA8vx+1M/DF+kpIw==,iv:fsAvfbhYSe00k12WlBMqT48fwy91Sbxz4GoUPz2vKYs=,tag:93yr9JI2zvoC0cjOe+lofQ==,type:str]
    additionalStaticClients: []
    extraStaticLogins: []
    staticPasswordNotHashed: ENC[AES256_GCM,data:58zWtmpxpdjQSOnD54wTWjo93Yw=,iv:q+p0D8BfeudSJ2lg/i387/SZuMjJkr9iehwVVlcX1g8=,tag:dn02oO4Kl/8qTy62glOfrg==,type:str]
issuers:
    secrets: {}
externalDns:
    awsRoute53:
        accessKey: ENC[AES256_GCM,data:Nq4pr6Rfz4py88TNkcY6+8DjSncaRduKTg1GN08=,iv:rceHlGbW6j9tK3e/65WjCiOBbXJSVRX9KbcChXjYaJk=,tag:T9mM4Y+vATv4sOWj2ofl/g==,type:str]
        secretKey: ENC[AES256_GCM,data:3Q7C4VDZhbtHnF21riFJPddHoYPxMJvSBD4FSGY=,iv:bIizVYCq2KiKym3jWkZaiZ15kY5tGQI6nVvUsX0uHp8=,tag:dbX34f2MpNS2MZegnGIdcA==,type:str]
user:
    grafanaPassword: ENC[AES256_GCM,data:N3N7DTwBuC2C/zhhslOHkFuFbec=,iv:+roG1oc5Lhli2NUsVtij9QH8W/PQEsBjiJDZJdAVkfo=,tag:keJRHyGNIk+Qae/PzIo1qw==,type:str]
    alertmanagerPassword: ENC[AES256_GCM,data:c9W6xAs/ScdwZ9X3YY/jCfjiXaU=,iv:MxDNqT/8sJxZuVuZ3PMv1Rfmm9Al6t4id7zS2L8WC1Q=,tag:QmBKznVVnv9L8TvXryQJIQ==,type:str]
kubeapiMetricsPasswordHtpasswd: ENC[AES256_GCM,data:JmkCT0BUTZdT7CMQ+kS3IHaG3cwLgGVnOCSWLHpDAJlZ7XWMaasFRDB8DajUUoIZE5zjfOZPrQq2HM1NZtiZFa0oHuVo/TQZ,iv:V3LtQndBnmz+b3OwcJ/rE6k9SuQPB2cLw0Ek5L6QmJQ=,tag:hhCrZJwiLld4qq3QIlMBVA==,type:str]
sops:
    lastmodified: "2025-10-13T12:42:22Z"
    mac: ENC[AES256_GCM,data:4/xQPJtQXZrWrPZZzaZMsaphsZqNHBbCnIp6tUk8+iqf51tp6+eTmaWaVCfWdc+hyIsITPMUR3sc03lIDFrjUb7i2awsbjQOHgKKPj51H8K4fvDHLTih+YpWZjNEmqRgw2ENpBVpl95HlKV95ETl0aNqf3L4ncnEOEyVPIkpJxE=,iv:6Dz9cNMEkf77hysMlFDKvSAJl99Blgl6fHlPyPWsY3M=,tag:s3TG44nrWhRC36zj2ScQbw==,type:str]
    pgp:
        - created_at: "2025-10-13T12:42:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5KuUEhhf9McAQv/VjtTgPhO7DvgsqPdmcb2YuS2eJ4cUzEVRdmpm74M4M8N
            gxz695Lw6kGc+vb6qIuGFw9lQuOMyRZtu3dHZgiKQDkE/CvyOiomFGE9VUaoLPFG
            m4bosATEufLzFyetSOIExSp1ZTYKgV70iCxD2ijQAvSS5tGpA3wg4ZYCMfQ3qMRq
            Kdya3ItGtBr+hrCe65Mn6SiimMevCaTirQqA6IwXdIWcgemuIQGn0IJQwwQvYyIE
            rw9V1+vkWoG+IJklYQo7nu12S80gbz8K7KL4La4giQRQwC1EdvxtLi7Lg3jH6woO
            RW42DsjX5nDmD0zAIfz6MXRTckYUvTDrUgSXu2ctYorl6woDbBPNhFjhCQ/ASwEl
            JPpgoIgEy+qlj32hrwQsvltZSKNWRwNjpQdPsrUFdtGCpDIV0aGpEeCcLy6esOsQ
            aFNpvf1HVw3DKk5hV+tcnssL06+rHdwb7m77igFO/NSy818QEyB4iQ3ipP7+fXHM
            zWJJANiYSDWHwGqGyR3Q0l4BwWtniO9rIDbkwOOD9E61Gl9GiGyS1Qogy3sxGy84
            ZDGkwdcTpUF6BbBqhWVxfnRlwOj63Hhp+3o20alspMCfPToj3m347DX+ijr8Z2EN
            Gwg5UGLrQUiW2eXVqssB
            =awwi
            -----END PGP MESSAGE-----
          fp: 0EADCBADE0DE43E85DF02CE61BF5F0A3E68EBF06
    unencrypted_suffix: _unencrypted
    version: 3.10.1
