# Changes made here will override the default values as well as the common config for this cluster.
# See the default configuration under "defaults/" to see available and suggested options.
templates:
  amsNamespaces:
    - jaeger-system
    - postgres-system
    - rabbitmq-system
    - redis-system
  tolerateElastisys:
    - key: elastisys.io/node-type
      operator: Equal
      value: elastisys
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: elastisys.io/node-type
                operator: In
                values:
                  - elastisys
  tolerateSystem:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: elastisys.io/node-type
      operator: Exists
      effect: NoSchedule
  affinitySystem:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
          - matchExpressions:
              - key: elastisys.io/node-type
                operator: Exists
calicoAccountant:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: elastisys.io/node-type
      operator: Exists
      effect: NoSchedule
certmanager:
  tolerations:
    - key: elastisys.io/node-type
      operator: Equal
      value: elastisys
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: elastisys.io/node-type
                operator: In
                values:
                  - elastisys
  cainjector:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: elastisys.io/node-type
                  operator: In
                  values:
                    - elastisys
  webhook:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: elastisys.io/node-type
                  operator: In
                  values:
                    - elastisys
falco:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: elastisys.io/node-type
      operator: Exists
      effect: NoSchedule
  falcoSidekick:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: elastisys.io/node-type
                  operator: In
                  values:
                    - elastisys
fluentd:
  aggregator:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: elastisys.io/node-type
                  operator: In
                  values:
                    - elastisys
  forwarder:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: elastisys.io/node-type
        operator: Exists
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
            - matchExpressions:
                - key: elastisys.io/node-type
                  operator: Exists
hnc:
  excludedNamespaces:
    - jaeger-system
    - postgres-system
    - rabbitmq-system
    - redis-system
  manager:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: elastisys.io/node-type
                  operator: In
                  values:
                    - elastisys
  webhook:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
ingressNginx:
  controller:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
  defaultBackend:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: elastisys.io/node-type
                  operator: In
                  values:
                    - elastisys
prometheus:
  tolerations:
    - key: elastisys.io/node-type
      operator: Equal
      value: elastisys
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: elastisys.io/node-type
                operator: In
                values:
                  - elastisys
  alertmanagerSpec:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
trivy:
  tolerations:
    - key: elastisys.io/node-type
      operator: Equal
      value: elastisys
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: elastisys.io/node-type
                operator: In
                values:
                  - elastisys
velero:
  excludedExtraNamespaces:
    - jaeger-system
    - postgres-system
    - rabbitmq-system
    - redis-system
  tolerations:
    - key: elastisys.io/node-type
      operator: Equal
      value: elastisys
      effect: NoSchedule
  nodeSelector:
    elastisys.io/node-type: elastisys
  nodeAgent:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
opa:
  controllerManager:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
  audit:
    tolerations:
      - key: elastisys.io/node-type
        operator: Equal
        value: elastisys
        effect: NoSchedule
metricsServer:
  tolerations:
    - key: elastisys.io/node-type
      operator: Equal
      value: elastisys
      effect: NoSchedule
kyverno:
  tolerations:
    - key: elastisys.io/node-type
      operator: Equal
      value: elastisys
      effect: NoSchedule
gatekeeper:
  allowUserCRDs:
    extraServiceAccounts:
      - namespace: metallb-system
        name: metallb-controller
networkPolicies:
  global:
    wcApiserver:
      ips:
        - 0.0.0.0/0
    wcNodes:
      ips:
        - 0.0.0.0/0
user:
  namespaces:
    - example
    - production
    - staging
  adminUsers:
    - admin@example.com
  adminGroups: []
