s3:
  accessKey:
  secretKey:
user:
  grafanaPassword: somelongsecret
  prometheusPassword: somelongsecret
  alertmanagerPassword: somelongsecret
elasticsearch:
  adminPassword: somelongsecret
  fluentdPassword: somelongsecret
alerts:
  slack:
    apiUrl: somelongsecret
  opsGenie:
    apiKey: somelongsecret
dex:
  kubeloginClientSecret: somelongsecret
