{{ if .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-trivy-vulnerability-scanner
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      vulnerabilityReport.scanner: Trivy
  policyTypes:
    - Egress
  egress:
    {{- toYaml .Values.global.dnsServerEgress | nindent 4 }}
    {{- with .Values.global.trivy.ips }}
    - to:
        {{- range . }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
