repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
        exclude: ^helmfile\.d/upstream/
      - id: check-toml
        exclude: ^helmfile\.d/upstream/
      - id: check-yaml
        exclude: ^helmfile\.d/.*/templates/|^helmfile\.d/upstream/|^helmfile\.d/state.yaml$
        args:
          - --allow-multiple-documents
      - id: detect-private-key
        exclude: ^helmfile\.d/upstream/
      - id: end-of-file-fixer
        exclude: ^helmfile\.d/upstream/|^tests/.*/.*\.out$
      - id: mixed-line-ending
        exclude: ^helmfile\.d/upstream/
      - id: no-commit-to-branch
      - id: trailing-whitespace
        exclude: ^helmfile\.d/upstream/|^tests/.*/.*\.out$

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        name: check scripts
        exclude: ^helmfile\.d/charts/opensearch/configurer/files/|^helmfile\.d/upstream/
        require_serial: true
        args:
        - --color=always
        - --external-sources

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: check spelling
        exclude: ^helmfile\.d/charts/hnc/config-and-crds/crds/|^helmfile\.d/upstream/
        args:
          - -I
          - .codespellignore

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
      - id: markdownlint-cli2
        name: lint markdown files
        exclude: ^changelog/|^docs/sbom.md$|^helmfile\.d/charts/opensearch/configurer/files/|^helmfile\.d/upstream/|^images/elasticsearch-curator/
        args:
          - --fix

  - repo: local
    hooks:
      - id: generate-cypress-tests
        name: generate cypress tests
        language: script
        require_serial: true
        files: '.*\.cy.js'
        entry: tests/common/gen.bash
        args:
          - cypress

      - id: generate-template-tests
        name: generate template tests
        language: script
        require_serial: true
        files: '.*\.bats.gotmpl'
        entry: tests/common/gen.bash
        args:
          - template
