citycloud:
  username: "set-me"
  identityApiVersion: 3
  authURL: "set-me"
  regionName: "set-me"
  projectDomainName: "set-me"
  userDomainName: "set-me"
  projectName: "set-me"
  projectID: "set-me"
  tenantName: "set-me"
  authVersion: 3
