---
templates:
  cert-manager:
    namespace: cert-manager
    labels:
      app: cert-manager

  cert-manager-controller:
    inherit:
      - template: cert-manager
      - template: cert-manager-chart
    name: cert-manager
    needs:
      - kube-system/common-np
    values:
      - helmfile/values/cert-manager.yaml.gotmpl

  cert-manager-issuers:
    disableValidationOnInstall: true
    inherit:
      - template: cert-manager
    chart: helmfile/charts/issuers
    version: 0.1.0
    name: issuers
    needs:
      - cert-manager/cert-manager # creates issuers
    values:
      - helmfile/values/letsencrypt.yaml.gotmpl
