---
templates:
  ingress-nginx:
    namespace: ingress-nginx
    labels:
      app: ingress-nginx

  ingress-nginx-podsecuritypolicy:
    inherit:
      - template: ingress-nginx
      - template: podsecuritypolicies
    labels:
      psp: ingress-nginx
    values:
      - helmfile/values/podsecuritypolicies/common/ingress-nginx.yaml.gotmpl

  ingress-nginx-controller:
    disableValidationOnInstall: true
    inherit:
      - template: ingress-nginx
      - template: ingress-nginx-chart
    name: ingress-nginx
    needs:
      - ingress-nginx/podsecuritypolicy
      {{- if .Values | get "ck8sManagementCluster.enabled" false }}
      - kube-system/service-cluster-np
      {{- else if .Values | get "ck8sWorkloadCluster.enabled" false }}
      - kube-system/workload-cluster-np
      {{- end }}
      - monitoring/kube-prometheus-stack # creates servicemonitors
    values:
      - helmfile/values/ingress-nginx.yaml.gotmpl
    wait: true
