---
templates:
  rbac:
    namespace: kube-system
    labels:
      policy: rbac

  admin-rbac:
    inherit: [ template: rbac ]
    chart: helmfile/charts/cluster-admin-rbac
    version: 0.1.0
    name: cluster-admin-rbac
    labels:
      app: admin-rbac
    values:
      - helmfile/values/cluster-admin-rbac.yaml.gotmpl

  dev-rbac:
    disableValidationOnInstall: true
    inherit: [ template: rbac ]
    condition: ck8sWorkloadCluster.enabled
    chart: helmfile/charts/user-rbac
    version: 0.1.0
    name: user-rbac
    labels:
      app: dev-rbac
    {{- if .Values | get "hnc.enabled" false }}
    needs:
      - hnc-system/hnc-config-and-crds # creates hierarchyconfigurations
    {{- end }}
    values:
      - helmfile/values/user-rbac.yaml.gotmpl

  dev-rbac-crds:
    inherit: [ template: rbac ]
    condition: ck8sWorkloadCluster.enabled
    installed: {{ .Values | get "gatekeeper.allowUserCRDs.enabled" false }}
    chart: helmfile/charts/user-crds
    version: 1.0.0
    namespace: gatekeeper-system
    name: user-crds
    needs:
      - kube-system/user-rbac
    labels:
      app: dev-rbac
    values:
      - values/userCRDs/common.yaml.gotmpl
      - values/userCRDs/bitnami/sealedsecrets.yaml.gotmpl
      - values/userCRDs/mongodbcommunity/mongodb.yaml.gotmpl
      - values/userCRDs/flux/fluxv2.yaml.gotmpl
