{{- define "crypt-provider" -}}
password = {{ .password }}
password2 = {{ .salt }}
{{- if .fileNamesEnabled }}
filename_encryption = standard
{{- else }}
filename_encryption = off
{{- end }}
directory_name_encryption = {{ .directoryNamesEnabled }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "rclone.labels" . | nindent 4 }}
  name: {{ include "rclone.fullname" . }}
stringData:
  rclone.conf: |-
    {{- range $provider, $config := .Values.providers }}
    [{{ $provider }}]
    {{- range $key, $value := $config }}
    {{ $key | snakecase }} = {{ $value }}
    {{- end }}
    {{ end }}

    {{- range .Values.targets }}
    {{- if get . "sourceCrypt" | default false }}
    [decrypt-{{ .sourceName }}]
    type = crypt
    remote = source-{{ .sourceType }}:{{ .sourceName }}
    {{- include "crypt-provider" $.Values.crypt | nindent 4 }}
    {{ end }}
    {{- if get . "destinationCrypt" | default false }}
    [encrypt-{{ .destinationName }}]
    type = crypt
    remote = destination-{{ .destinationType }}:{{ .destinationName }}
    {{- include "crypt-provider" $.Values.crypt | nindent 4 }}
    {{ end }}
    {{- end }}
