name: Bug Report
description: Create a bug report to help us improve Compliant Kubernetes
labels: bug
body:
  - type: textarea
    attributes:
      label: Current behaviour
      description: Clear and concise description of what you experienced.
      placeholder: Description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: Clear and concise description of what you expected.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimal example of that shows the behaviour you experienced.
      placeholder: |
        1. Go to '...'
        1. Click on '...'
        1. Scroll down to '...'
        1. See error
    validations:
      required: true

  - type: input
    attributes:
      label: Compliant Kubernetes Apps Version
      placeholder: vX.Y.Z
    validations:
      required: true

  - type: input
    attributes:
      label: Kubernetes Version
      placeholder: vX.Y.Z
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any additional information about the problem.

        Include screenshots if applicable to help explain the problem.
    validations:
      required: false
