name: Chart Upgrade Request
description: Create a chart upgrade request to update update a component of Compliant Kubernetes
labels: improvement
body:
  - type: input
    attributes:
      label: Chart to upgrade
      placeholder: e.g. dexidp/dex
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Reason for upgrade
      options:
        - label: Security patching
        - label: Upgrade to allow new features
        - label: Upgrade to prevent future issues
        - label: Other - _Write the reason below_

  - type: textarea
    attributes:
      label: Additional context
      placeholder: |
        Any additional information about the chart upgrade here.

        Minimum version required, Other reason for upgrade,...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Acceptance criteria
      placeholder: When can this chart upgrade be considered done
      value: |
        - I checked the migration of the new chart version:
          - [ ] The upgrade does not require migration steps
          - [ ] The upgrade requires migration steps
        - I tested the functionality of the new chart version:
          - [ ] The upgrade does not change current functionality
          - [ ] The upgrade changes current functionality
