name: Investigation
description: Create a task to investigate a new alternative or solution to improve Compliant Kubernetes
labels: investigation
body:
  - type: textarea
    attributes:
      label: Concept to investigate
      description: What concept, product or technology should be investigated?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Artefacts to capture
      description: How should the gathered knowledge be captured?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any additional information about the investigation here.

        Include screenshots if applicable to help explain.
    validations:
      required: false
