global:
  baseDomain: ${domain}
  opsDomain: ${ops_prefix}.${domain}
  clusterDns: 10.96.0.10
clusterAdmin:
  users:
    - admin@example.com
externalTrafficPolicy:
  local: false
storageClasses:
  default: standard
objectStorage:
  type: s3
  s3:
    region: local
    regionEndpoint: http://minio.minio-system.svc.cluster.local:9000
    forcePathStyle: true
calicoAccountant:
  backend: nftables
clusterApi:
  enabled: false
  monitoring:
    enabled: false
opa:
  imageRegistry:
    URL:
      - harbor.${domain}
      - quay.io/jetstack/cert-manager-acmesolver
  rejectLoadBalancerService:
    enabled: false
ingressNginx:
  controller:
    service:
      enabled: true
      annotations:
        elastisys.io/local-cluster: tests
      clusterIP: 10.96.0.20
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443
      allocateLoadBalancerNodePorts: false
    config:
      useProxyProtocol: false
    additionalConfig:
      worker-processes: "4"
    extraArgs:
      disable-full-test: "true"
    useHostPort: false
nodeLocalDns:
  customConfig: |-
    ${domain}:53 {
      errors
      bind 169.254.20.10 10.96.0.10
      template IN A ${domain} {
        match "\.${domain}\.$"
        answer "{{ .Name }} 60 IN A 10.96.0.20"
        fallthrough
      }
      cache 30
      reload
      loop
      forward . 1.1.1.1 1.0.0.1
    }
networkPolicies:
  global:
    objectStorage:
      ips:
        - 0.0.0.0/0
      ports:
        - 9000
    scIngress:
      ips:
        - 0.0.0.0/0
    wcIngress:
      ips:
        - 0.0.0.0/0
    externalLoadBalancer: false
    ingressUsingHostNetwork: false
    trivy:
      ips:
        - 0.0.0.0/0
  alertmanager:
    alertReceivers:
      ips:
        - 0.0.0.0/0
  certManager:
    letsencrypt:
      ips:
        - 0.0.0.0/0
  coredns:
    externalDns:
      ips:
        - 0.0.0.0/0
    serviceIp:
      ips:
        - 10.96.0.10/32
  falco:
    plugins:
      ips:
        - 0.0.0.0/0
  ingressNginx:
    ingressOverride:
      enabled: false
