alerts:
  opsGenieHeartbeat:
    enabled: false
    name: not-used
grafana:
  ops:
    oidc:
      allowedDomains:
        - example.com
    trailingDots: false
  user:
    oidc:
      allowedDomains:
        - example.com
    trailingDots: false
harbor:
  persistence:
    disableRedirect: true
  oidc:
    adminGroupName: admin
opensearch:
  extraRoleMappings:
    - mapping_name: all_access
      definition:
        users:
          - admin@example.com
networkPolicies:
  global:
    scApiserver:
      ips:
        - 0.0.0.0/0
    scNodes:
      ips:
        - 0.0.0.0/0
  dex:
    connectors:
      ips:
        - 0.0.0.0/0
  harbor:
    registries:
      ips:
        - 0.0.0.0/0
    jobservice:
      ips:
        - 0.0.0.0/0
    trivy:
      ips:
        - 0.0.0.0/0
  monitoring:
    grafana:
      externalDashboardProvider:
        ips:
          - 0.0.0.0/0
  opensearch:
    plugins:
      ips:
        - 0.0.0.0/0
