{{- if .Values.rcloneSync.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rclone-sync
  namespace: kube-system
spec:
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      app: rclone-sync
  ingress: []
  egress:
    - ports:
        - port: 53
          protocol: UDP
    - to:
        {{- range .Values.global.objectStorage.ips }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        {{- range .Values.global.objectStorage.ports }}
        - port: {{ . }}
        {{- end }}
    - to:
        {{- range .Values.rcloneSync.destinationObjectStorage.ips }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        {{- range .Values.rcloneSync.destinationObjectStorage.ports }}
        - port: {{ . }}
        {{- end }}
{{- end }}
