{{- $namespaces := keys .Values.constraints | sortAlpha }}
{{- $exceptions := list }}
{{- range $namespace, $services := .Values.constraints }}
{{- range $services }}
{{- if hasKey .allow "allowedCapabilities" }}
{{- $exceptions = append $exceptions .podSelectorLabels }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPCapabilities
metadata:
  name: capabilities-restricted
spec:
  match:
    {{- dict "namespaces" $namespaces "exceptions" $exceptions | include "podsecuritypolicies.renderMatchExceptions" | nindent 4 }}
  parameters:
    requiredDropCapabilities:
      - ALL
