{{- $namespaces := keys .Values.constraints | sortAlpha }}
{{- $exceptions := list }}
{{- range $namespace, $services := .Values.constraints }}
{{- range $services }}
{{- if get .allow "allowPrivilegeEscalation" }}
{{- $exceptions = append $exceptions .podSelectorLabels }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowPrivilegeEscalationContainer
metadata:
  name: privilege-escalation-restricted
spec:
  match:
    {{- dict "namespaces" $namespaces "exceptions" $exceptions | include "podsecuritypolicies.renderMatchExceptions" | nindent 4 }}
