objectStorage: {}
grafana:
    password: somelongsecret
    clientSecret: somelongsecret
    opsClientSecret: somelongsecret
    ops:
        envRenderSecret: []
    user:
        envRenderSecret: []
harbor:
    password: somelongsecret
    clientSecret: somelongsecret
    xsrf: somelongsecretandsomelongsecrets
    coreSecret: somelongsecret
    jobserviceSecret: somelongsecret
    registrySecret: somelongsecret
    internal:
        databasePassword: somelongsecret
    registryPassword: somelongsecret
    registryPasswordHtpasswd: harbor_registry_user:$2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
thanos:
    receiver:
        basic_auth:
            password: somelongsecret
            passwordHash: $2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
opensearch:
    adminPassword: somelongsecret
    adminHash: $2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
    clientSecret: 7OL6CjsfTgAZPgfGNe96
    configurerPassword: somelongsecret
    configurerHash: $2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
    dashboardsPassword: somelongsecret
    dashboardsHash: $2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
    dashboardsCookieEncKey: abcdefghijklmnopqrstuvabcdefghij
    fluentdPassword: somelongsecret
    curatorPassword: somelongsecret
    snapshotterPassword: somelongsecret
    metricsExporterPassword: somelongsecret
    extraUsers: []
kubeapiMetricsPassword: somelongsecret
alerts:
    slack:
        apiUrl: somelongsecret
    opsGenie:
        apiKey: somelongsecret
kured:
    slack:
        botToken: ""
dex:
    staticPassword: $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
    kubeloginClientSecret: somelongsecret
    connectors: []
    additionalStaticClients: []
    extraStaticLogins: []
    staticPasswordNotHashed: YkQoVgNomjbqad16W6Fp
issuers:
    secrets: {}
externalDns:
    awsRoute53:
        accessKey: set-me-if-externalDns-enabled
        secretKey: set-me-if-externalDns-enabled
user:
    grafanaPassword: somelongsecret
    alertmanagerPassword: somelongsecret
kubeapiMetricsPasswordHtpasswd: kubeapiuser:$2y$12$deOdppfS.5sd7jZjbEQQPO7UoVvnSN2v8ZyJxmGPj80mffjoEZzvG
