objectStorage:
    swift:
        applicationCredentialID: ENC[AES256_GCM,data:5JV6CzF5q5skfzOSyo8=,iv:TYnhZN8Iv3aXC+Q21cDvCHPt2jQb6gB4ebOdS2xTVD8=,tag:zsNw3lGq+HozsZm9Qygaow==,type:str]
        applicationCredentialSecret: ENC[AES256_GCM,data:LU0Hpi2Oeaaeax6SWEo=,iv:fAKVxRfQXiHJapZ+3MG3HuHCqXL64pppkwJpvbwhCJ0=,tag:REEKPl2ZO6kXsiavic9hPw==,type:str]
grafana:
    password: ENC[AES256_GCM,data:kepUbghFpnWOC+PLONQpwlj93gE=,iv:U1Br9nTQG5l4T1vz5CtURw99NL/X06e0+GdvKH/qVvU=,tag:+qu79y5xMBOoebHfIA65rA==,type:str]
    clientSecret: ENC[AES256_GCM,data:SC5a64PkwIskj5jX5gV/cBA70uY=,iv:s/dokeWIASgVdupchqyXBRdN5hqLEwrGPXOJYrL2ogw=,tag:xOZtQyGGJcJP7Y5AKIxWCA==,type:str]
    opsClientSecret: ENC[AES256_GCM,data:vmNu7CmXT/TljJfO0nQz9AuRi9w=,iv:VBZayQVJE6rCQqDpNLJiFvszRpkROFFUGR7mXYwEPvg=,tag:pEuYag9CfWXw5ndmmCJIFw==,type:str]
    ops:
        envRenderSecret: []
    user:
        envRenderSecret: []
harbor:
    password: ENC[AES256_GCM,data:0p7J4ohf+/wsqlOZdp6qcpiU6zQ=,iv:vUTtH2nBTpw2YSxKHPK1Cd6SxnZzDvLem/u9t2zj6Ik=,tag:s6v2sMhLRvUAydp0Df8kBQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:2L3VxQ2BYUpSaXv/m4C9jNvb0Uc=,iv:7L4io+7JjHfo1+JJhh4dbditqyawhZY1CSnVNXGuuCA=,tag:pVxJVY2UGTwUE5Cd8Ed/sg==,type:str]
    xsrf: ENC[AES256_GCM,data:nn4XbAxExVyDhcaqVOGqR3wWXrYCa6tP0UO4yV02doY=,iv:SJI1h3Ts+Qlc4rbaSy5f8T5g76/M8OgC7ncN7SlfPIM=,tag:TYboffVkPUCwWafvnmeu0g==,type:str]
    coreSecret: ENC[AES256_GCM,data:uGhk/q1RYbngT0q3Z/BZ52iawKs=,iv:AHR3/WQIopfGZ9B0mRfROdCXDsdCUH8a0rtloqK3tpU=,tag:y6B9D9GjojUszSFeNbTT6g==,type:str]
    jobserviceSecret: ENC[AES256_GCM,data:AkuYfyIYlpt4bbKAMgmuULf5dHY=,iv:zI+dRB4Tb6uFbi7YFI7yrcnpjHnXAyWbfe/gML3JPyo=,tag:C5W4WwC52hkhWmgygjKCoQ==,type:str]
    registrySecret: ENC[AES256_GCM,data:dwa9HndGBvKUiY2X1orQSY6pcTg=,iv:FTFeVPgIVzImpXRYXFGW2Iupr8ut/6CFBlNUMofUaQQ=,tag:Sknpe6D52L6Q3OSr47n4WA==,type:str]
    internal:
        databasePassword: ENC[AES256_GCM,data:386rn8a6McqvtJ8S0L2711sdeow=,iv:Q4+NX43ZuyWLqvH2vPRIiMYGCCf/OB8dyW8gEKcA0nE=,tag:skYi34MkLbztgQKQdNPy3g==,type:str]
    registryPassword: ENC[AES256_GCM,data:rKITfi40KuI/gU9nTw0DRym/j6A=,iv:EBKwYrsuCaaKyAmY+4yZFgn1gUdbj0ZRCAcHXZDAYNs=,tag:gXge+xlQlIGAYco06Vu0kg==,type:str]
    registryPasswordHtpasswd: ENC[AES256_GCM,data:HFSFTdKZt7hepK/FoA6ppzMTGlmV9RGShKqSvJPp10Bx/081q5ep/5Co87/k1X2k+zZ1M7LumOxcmC9v3mGBMn7mHulIW8RCICKyu3eZfVEq,iv:yaJUcGCVFuobcZkXTmcv+icWHJRBTxJ+VLmJ3m08O3k=,tag:ANbmH+bOsqaM0OUWnFRFlA==,type:str]
thanos:
    receiver:
        basic_auth:
            password: ENC[AES256_GCM,data:p+a8ZqT+lNycCQdxTu/vNjxTTRc=,iv:qLBRQWGuSkHw+AUXUGH6RRU3yx9O7KALJesjn2ggTT4=,tag:Jk0Vsiz4F+aweV1j7JkFeA==,type:str]
            passwordHash: ENC[AES256_GCM,data:WWwcW1igJx0EyfGyCY3gloM991XrmYY+6CQ81ZXzNRG41pJCDg==,iv:yMcooEVyNUTkIJoZvxk2TjxtCnBHtuESUn3d9NPQols=,tag:escQWCy6Go7te8kI07x1dw==,type:str]
opensearch:
    adminPassword: ENC[AES256_GCM,data:u/X+fgERcHC7rWvYO0kwLc61QSw=,iv:JQ2kStJjiwyRjiewUrgWkMtSkNvMHTFV6pivUJBW8No=,tag:PTGQHUbUcHfB2TaqxmW//w==,type:str]
    adminHash: ENC[AES256_GCM,data:UPV2cOaAx6bX2rvdeXmMTxMVJ3bHUmlUze5++URt2xTp3lwp4+mCi4sH+YS3C0OMGZT4do57nV1Gy0fg,iv:EQXXxmjAOFdZ22REKjKBoxSEKEt6XMGS5RuskjzaGak=,tag:QkeDM8M5qmMqmwK6rCqXHg==,type:str]
    clientSecret: ENC[AES256_GCM,data:+aC/Ws2kP/XFf9Yes6cJdEnZjcU=,iv:v2HHAqG6a8NkXyPC0K1zrDOtEXupJxqKtfPG80Gpmzc=,tag:Ex0MLcaFTd+mntxk+SQTwA==,type:str]
    configurerPassword: ENC[AES256_GCM,data:wHgWkKP0Fi68qR9IHjXZuhjiL2Y=,iv:iitXjAZg2k29wFo3WFmX+EkWtvkZVLIoCmph6vf7hxw=,tag:e18NZetLN5ajx/Tx/Vbpkg==,type:str]
    configurerHash: ENC[AES256_GCM,data:vNDiQriV/mCw41letPWRL7lQ3kFbWiFzvzXIZrLQ76pTHxMqUQSpRHkvGzT6yAi6XO9mE3HkIDFdDsd+,iv:t6ElN+JktEABAvloXw6pCiGJif186TYrTJTXLl5SnRs=,tag:ToPuIp0sUA+NubC5MRTwpQ==,type:str]
    dashboardsPassword: ENC[AES256_GCM,data:0px1OzN+TTAho6eoZ97l39yNXPI=,iv:yvz1NZDKABnt2+teBIo3Bv2+f0vKpUaM1RgyLWY0szg=,tag:8y7lwqiiB9a30fop6bmCpg==,type:str]
    dashboardsHash: ENC[AES256_GCM,data:rD6G2My4mw2RNVPEtl2PMvj9dRFo7IYM11Nkc5mgaQxsbl9JS+R34exz4ViUmFOkRtcwMvCRFDL+2lPR,iv:aTolf7JRIMMCHq+a4zP3xu9rzG3WCy75pjTYavFjYtU=,tag:ax7JxMnxLKZKuTpcmPVlKg==,type:str]
    dashboardsCookieEncKey: ENC[AES256_GCM,data:rWlcK2mwOdhytY1K++Jo0Ay+sQ1Sbc/4ALUNwnx/H1I=,iv:nAsq0txoNlzUKAQMU5Pxjf7giCwaO7YJi58sTd1Znmw=,tag:6+1g4rx5FDuT346MdS788w==,type:str]
    fluentdPassword: ENC[AES256_GCM,data:dU77AwLvrRKeey8PeCOPymJvsBY=,iv:e+ATlb3Qi/F1DMYYtQphJXdb7zesoeao2ab/IM3VXSw=,tag:stOUwMhx7ZipE4f2hIUc8A==,type:str]
    curatorPassword: ENC[AES256_GCM,data:Ja48B6BjD4uXhCXMfPmjzhWWSmg=,iv:IFglQsgpTHwg5l29WreFn+TY0an+WimJ4mBhtWJm13o=,tag:EiqZemEoJ05gwWDruDkUiw==,type:str]
    snapshotterPassword: ENC[AES256_GCM,data:Bi4n9SBnJgEmgAjxYTg4ubyG7BQ=,iv:dYMCdETEcn1A5XmtTAQOXeVmPPT4evc2uMBQrETcyvg=,tag:LPDOxKzrpKHrFKancFxINA==,type:str]
    metricsExporterPassword: ENC[AES256_GCM,data:xrQKZH79PytfPGNeMCN5gcYdYzo=,iv:K1Otve/5V78q+dB7+63MJLR3b4rDXBFVe8zpq9XUJGQ=,tag:MuPRpHMBTmbc9cjPwcbwEQ==,type:str]
    extraUsers: []
kubeapiMetricsPassword: ENC[AES256_GCM,data:x7gvGz05ZprsDCHXhtTQcjF+d9c=,iv:s+P8TzHq55A4DSh6pUBYgQdQPn5ZsAQFZt3cJgLt0k8=,tag:l3MfdYsrQroL7DGa7IxHeQ==,type:str]
alerts:
    slack:
        apiUrl: ENC[AES256_GCM,data:HZJjxG1ytpW6muqW36Y=,iv:gw73CgesKMclmN/+gW+STzks2uRp8bgUwbMZhy/fGC0=,tag:bkPoypchhHPkJUeWGKctWA==,type:str]
    opsGenie:
        apiKey: ENC[AES256_GCM,data:PG1R5t4V,iv:fPxcJHJ8kZbfKyjTCKvT1Ze/RbTdFq+XEeho0osmnIk=,tag:+QZLAPqMxsS4Rur9FAsCaA==,type:str]
kured:
    slack:
        botToken: ""
dex:
    staticPassword: ENC[AES256_GCM,data:5AyeoX1gRagLoxRT86KZWFeewFxrUX32wdIWnpm2lQU51Aw/XMigeq8ZQQGBg0ufE5wW6ROp5CdRk1Cu,iv:jMzWlNO7ZqnIwG+UxEV79ltPgP8IlzHX68Nf4T1Pyjw=,tag:vsqdPRgZQjBm9BFhcqdjPg==,type:str]
    kubeloginClientSecret: ENC[AES256_GCM,data:VhCdPv2fQkGOSBU60p3BdXPt4EQ=,iv:EMTAMcf2ui/oiee5TX/4KAliApEgee8BEnbWQFj95BI=,tag:aztMBhBv/qSaY6BepIlaYw==,type:str]
    connectors:
        - name: ENC[AES256_GCM,data:NnF21GNBysGk,iv:vPcwnYqetAs8AIp3FB7eObu9ZsTbpVlHHzvizCFl318=,tag:Dq3Epsdb9kip8x9oJWOPvw==,type:str]
          id: ENC[AES256_GCM,data:dbXPmXbsqFXpI6vDA41glQ==,iv:ALDxV/VmiK3H/DdX7G6zxekIDFpwXp2FzzIwh7WroWc=,tag:GnreTWN1Cv15/dpl1ERYiw==,type:str]
          type: ENC[AES256_GCM,data:43I509M5,iv:7+PC7OEAmYQm/YA6TUJzCOfD8N3horbKEMznjolpRzM=,tag:cLaGk6tEMTzbtajJW5MnNg==,type:str]
          config:
            clientID: ""
            #ENC[AES256_GCM,data:F8y8vk7efm4cfWeSxFODyqU=,iv:36qukoKIRF3FOZLOterKDER7V6NWkonsokvhACzLKbc=,tag:mKIJqmJ9JTsdoQ62rzS7yg==,type:comment]
            clientSecret: ""
            #ENC[AES256_GCM,data:J0oETQVvpEhZU7iDTHuQfJ3vI8VW,iv:jjQyFjHMrTsBcIoJQv0T8jF+jnZPlPoi1G2irngS0ow=,tag:eNxkZQffKQO12hNXgAa4YA==,type:comment]
            redirectURI: ENC[AES256_GCM,data:ib681XAUa1JQEH5GVEe4nCv/UpRaf2f6JgXZXj63V0M=,iv:kF8Cg2HLLVcyQpB+oO/rDXuijjOkBIL2DGOOg0oIFFg=,tag:MnySyghxa51j7Riu8BATkw==,type:str]
            #ENC[AES256_GCM,data:FYjgyXfmnq2YS9eCmWfITu6M42qrMFbsBQ==,iv:U8aFnBv510bx0xrAjbIpjDVhYY8N29BWaKX9sBhtdAc=,tag:djD2kEnA0sJwlYtBBxYe0g==,type:comment]
            serviceAccountFilePath: ENC[AES256_GCM,data:4jWRxiN+E8+WHO3BdU7HmjtPB2kien8=,iv:eJSDwaEGCK6JPxbBnsQivtOrRtnB/Vm6eDikzUKfdxg=,tag:Q+r5mjaX8Ss+WwVa+CLWyA==,type:str]
            adminEmail: ENC[AES256_GCM,data:pJlWKcXL8bYeOwyVWhCDQoqE4gjo5CGTHzwHD9WnDQ==,iv:EFAPL4HD+6TB9ALLOWDN2+QsCi8CGCBY1OXzSLLt5iE=,tag:+NWfTg24XBMk3EkRZ71EEg==,type:str]
            groups:
                - ENC[AES256_GCM,data:qkyVxk6gDA+J9xA9y9u3XAH5TSacHVeu,iv:/CnnN3gVQvFcg73YeJ1rX8vRTq/CaNUpY5z3tQwI+X0=,tag:ZSkjCSh7NOL/eufCMebJqw==,type:str]
            #ENC[AES256_GCM,data:KyjMRrACFvpRhmeJPl6hDA==,iv:c/nusiokQyUBb6hqWDUab11KGyvtRtUMLPJkKicSrXY=,tag:Xz3GrCqaVtGWolhXQtkptw==,type:comment]
            hostedDomains:
                - ENC[AES256_GCM,data:/C5IHRMbg3xFu2Fulg==,iv:vKfMzIJzIUQvugw5aVDRtCDzEYsB21Ek6F/BckjWSkY=,tag:vMJIaDVaMMvs6b21eTvlTA==,type:str]
    additionalStaticClients: []
    extraStaticLogins: []
    staticPasswordNotHashed: ENC[AES256_GCM,data:wrY+XvbHr57c5ivj6UKanfe3E4o=,iv:wkhowcIf+SgrNf2jbyVw2mTMzkcHiIOxKWdksMpdfN4=,tag:tG2qYmJ3VRqHWIW8fTpQ2w==,type:str]
issuers:
    secrets: {}
externalDns:
    awsRoute53:
        accessKey: ENC[AES256_GCM,data:xcPPZeTFbKMEGlrVoQ1I8dB4mIwiTJ2xN9JCQds=,iv:7Nwp0R+czunHbttIZ1LCuiv0hrm4DgBcga315zdv3Oc=,tag:bY7LgWM8Iey9fCuxc4nk6w==,type:str]
        secretKey: ENC[AES256_GCM,data:wh7bb+4jyVDiwTDF6bif+QNe/KtCXfG+RXTQik0=,iv:5pqI5cR+h9/Wl5qSHNhMRwed2cnLzglNJ+sGCsl5Kh0=,tag:TfJj9Fa2bKEYc2oatwewaA==,type:str]
user:
    grafanaPassword: ENC[AES256_GCM,data:OL1t6N4kFS9B//Vl7hOR9FXeInY=,iv:X3o2SSN4OReUtyb5iYi0wth6TYegynMiFn9+QWp4Ip8=,tag:PZvs4J6qynNvTQ1ZYRhGrw==,type:str]
    alertmanagerPassword: ENC[AES256_GCM,data:eivyG7oOMp1s9QzDlHBKgSBca84=,iv:g/DEcPcAxP1ZD1B/1tvkPlqo+epuoPjJzp/1qeS5Gxs=,tag:yTO3Ne0k39UnoyRU94mD/A==,type:str]
kubeapiMetricsPasswordHtpasswd: ENC[AES256_GCM,data:qtCBnZzT8WqaJA71wyKiwCFAumW6YWPkX1pz5B9luNuFCn+qBv9Itzh7QlY1Eyme9Odjm+PyZsLlth2YCSk4DYZh5v2ZuoRr,iv:EpgJrtKR+xcltyPuxonyBsxdVihCsodMZsC8QDZ7Ilc=,tag:f7gyD97d3pt/EMgNizY65w==,type:str]
sops:
    lastmodified: "2025-10-16T14:13:42Z"
    mac: ENC[AES256_GCM,data:RkZunr//3UxbsNbybXbrrpRYoYizPxg1rHQomUZVEtpvQFEzfveKAZd0ZxWW9BMmsuFdGM3OC1OkLhnX4JJHGNa8dXcXNQwRpQK5Uk/0CqflYAs42n5MMXrRNI0uwCBak2XBi8drYGBaxlS8pvXq8QHyUbNQlM6s6XqlzANfIB0=,iv:fql5QtFsA4xwe+/+UgVt4PDrrqhk0Omt89SxFrU8n8U=,tag:HHZwfIbuXMOknLyu9IirLg==,type:str]
    pgp:
        - created_at: "2025-10-16T14:13:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5KuUEhhf9McAQv/aouUTANIbuCLTPSfRp+tGpdj0OS2Ezu2DZ78/MM+DXHc
            MZJInJniqK4rGPLQ44D2dnTZimwHSq/d6iVZ0h8flcHCaNHnnSCBT8M5yCH26o+4
            EoZR5mDawfKQ5TF8jbLrk0C4AT1gYc+zncx2sSriBghbKGVO9W1AWGr+k+92sg5w
            8AAk8mMz3qr4f1KkbFs1QNZYPIurcfxNSTYJaQEnHiLa9tcAJLONHvdkWmNi/w0z
            QKILrra/nf1Fn0AwA6I/5HIlErHiBgmWsTLcQy2M1jIHgsYn9+x49vwip8sQ6I4t
            EpVOgHx7UBFdGxSsNjwjCMPXjqabn0swaVbp13kH0cnNdBWmVrjwDIAA0JUB6e9F
            kou1uzcd8DOMp01PonQKn+9rUfiP0PUQDGXzYB3I3NgwCovGB2dFTcT43D/K2bJe
            4fn8WkDFwhAKv4gIolv0DPBEjMMp9Wqe5Iaf082uaRtEB8TfgLhQ8sbGqqeGpURs
            yi9J3c5hWpl0GvthFCPf0l4BE/2DpzKtVkD+pU9YoA79raF3hK+O8EYycYYnaowi
            aHyJ3L3E9BCrZ8p1QJ4GB6y5r79RrIjxToJ77kXIhBrO3CdxYfd7Kje0J2Qymdbr
            9JnYDlxv6xnKwm2f1LPB
            =h8vj
            -----END PGP MESSAGE-----
          fp: 0EADCBADE0DE43E85DF02CE61BF5F0A3E68EBF06
    unencrypted_suffix: _unencrypted
    version: 3.10.1
