apiVersion: ENC[AES256_GCM,data:kjQ=,iv:y9eQR3owcbARa48GPVcLfoL4r1RFVLWpiihMUOolguU=,tag:DLUoiQjpGCgVP2J36bUs9g==,type:str]
kind: ENC[AES256_GCM,data:jLI0ZdVf,iv:wn15DyT9JwqfWVODi+E4O86hIIQMKmK8nNH5ALECjBk=,tag:fnhdO9pZiqPLq5B40/XGQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aa4qdKbAuPhS,iv:xkC0cWREOzeSmyQyydvTKt8QOkZc2E5vAbK39qW/WzE=,tag:kjbqBu7v1RtlNlQD4tqi0Q==,type:str]
    namespace: ENC[AES256_GCM,data:IJpi,iv:VwUoBKriBeis2CjawmIVrqZmZTCIsPcShCrqBEUI/MQ=,tag:9G/6GDfWqojPqMHlVdPA+g==,type:str]
type: ENC[AES256_GCM,data:fFs+FKp3,iv:wSzmr5oEqtOWOeq50bwSPx0SE3cKV6gNWYrj/YqQhgE=,tag:o6gLLMwp18qu6NJPSyrp6w==,type:str]
data:
    sa.json: ENC[AES256_GCM,data:zB+izxjM2y8rt841HZtP,iv:SUeRrDL++sIH81dijDvqiy9A8+FgmLAbjxIIf5mRBs8=,tag:AHvflYCCRCRJLjUb0ZRZdQ==,type:str]
sops:
    lastmodified: "2025-10-16T14:13:01Z"
    mac: ENC[AES256_GCM,data:UMsT/jE63TeQbzrFZy9zrSoGciLf7cQDGuqFGBCW7lhwKzR/B8uIXQ/K0aOZlGiAu+MFENVshxEfkc0dOaDit6rEMD+Pbb8QAHGvjOs0LpAYR2XEWcddS35E+rAD/lo71m21DxREAGDRMqqerQRPESoAscR3MXDEnGBHIp3D5gs=,iv:D+ssyO+wL6jzJ6RxgUgaJycgnMAZxYWby21jo4gSSfc=,tag:Oy8uUSE7zlvH4/LODw9RnQ==,type:str]
    pgp:
        - created_at: "2025-10-16T14:13:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA5KuUEhhf9McAQv9FHaCaFCbfR8SWJXlEDDclZuS4G5JGjj9oBCO+0XWjRXP
            6DpgGe2xAqQdXE/Flk9tkcDoSgnLHTd+vrsKJFmYt94UK8rpL2uxjuCsCDTMd4oT
            1p1PTh7Y6wyWymSQV5iH/8FZrJlD/Q8gtadcqVadWVxG/k9kmqatgoQKv8U+7Iox
            aEp4pe9hxkICgQCyCVloPnK6pBKM/7RFuRcR3x66GsksdPcpYJBs/kMHNdv1o7pN
            Tl5xEmlEPJy3Ackm4rIdnTOl3M1puaz9fOvq+p720r/YIBxUnvi87o2uRi6R4sAa
            Jr5RY8emrp1YsS4IoNoTwN1w7ZL94DAebBxUcEeC5Ek4bMT/HB4D/R+gSix7KJnm
            AvTXfkDt/WmYL8kBZXSDHobQZig1pRjsaMF/I2/LnPIWL72GncOeGFOEy4ndtuEF
            80rUsZNF+f1YHarHia3o90U2SqoOEI5Bu5F7i6zIA11gFS6ZFoTHCSKKaJhKqJuv
            PlDEq8tZlF7adbEX1oFa0l4BtFem5mvhywvwH0HT6bZhOLhsdedr/orSQpMpcqI1
            TuwnjF7F+CHqOBT3qNUgKoli752Gx2zQ1IIvU1/ML0yCpvq0jqi0vz4/wwVSdt9x
            Sl18IBpoyL89a4We98dc
            =xrU4
            -----END PGP MESSAGE-----
          fp: 0EADCBADE0DE43E85DF02CE61BF5F0A3E68EBF06
    unencrypted_suffix: _unencrypted
    version: 3.10.1
