# all-in-one cluster
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  ipFamily: ipv4
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        listenAddress: 127.0.64.43
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        listenAddress: 127.0.64.43
        protocol: TCP
  - role: worker
  - role: worker
