{{- if and .Values.defaultRules.create .Values.defaultRules.rules.opensearch }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "prometheus-alerts.fullname" .) "opensearch" | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ template "prometheus-alerts.fullname" . }}
{{ include "prometheus-alerts.labels" . | indent 4 }}
{{- if .Values.defaultRules.labels }}
{{ toYaml .Values.defaultRules.labels | indent 4 }}
{{- end }}
{{- if .Values.defaultRules.annotations }}
  annotations:
{{ toYaml .Values.defaultRules.annotations | indent 4 }}
{{- end }}
spec:
  groups:
  - name: opensearch
    rules:
    - record: elasticsearch_filesystem_data_used_percent
      expr: 100 * (elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_free_bytes)
        / elasticsearch_filesystem_data_size_bytes
    - record: elasticsearch_filesystem_data_free_percent
      expr: 100 - elasticsearch_filesystem_data_used_percent
    - alert: OpenSearchTooFewNodesRunning
      expr: elasticsearch_cluster_health_number_of_nodes < {{ .Values.osNodeCount }}
      for: 5m
      labels:
        severity: critical
      annotations:
        description: There are only {{`{{ $value }}`}}  OpenSearch nodes running
        summary: OpenSearch running on less than {{ .Values.osNodeCount }} nodes
    - alert: OpenSearchHeapTooHigh
      expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}
        > 0.9
      for: 15m
      labels:
        severity: critical
      annotations:
        description: The heap usage is over 90% for 15m
        summary: OpenSearch node {{`{{ $labels.node}}`}} heap usage is high
    - alert: OpenSearchDiskWarning
      expr: 100 - es_fs_total_free_bytes{pod=~".*data.*"} / es_fs_total_total_bytes{pod=~".*data.*"}  * 100 > 80
      for: 15m
      labels:
        severity: warning
      annotations:
        description: OpenSearch disk full Warning
        summary: OpenSearch disk full Warning
{{- end }}
