# Based on https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
{{- if and .Values.defaultRules.create .Values.defaultRules.rules.thanosMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: thanos-prometheus
    role: alert-rules
{{ include "prometheus-alerts.labels" . | indent 4 }}
{{- if .Values.defaultRules.labels }}
{{ toYaml .Values.defaultRules.labels | indent 4 }}
{{- end }}
{{- if .Values.defaultRules.annotations }}
  annotations:
{{ toYaml .Values.defaultRules.annotations | indent 4 }}
{{- end }}
  name: {{ printf "%s-%s" (include "prometheus-alerts.fullname" .) "prometheus-thanos-rules" | trunc 63 | trimSuffix "-" }}
  namespace: "thanos"
spec:
  {{- .Files.Get "files/thanos-rules.yaml" | nindent 2}}
{{- end }}
