apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-label-enforcer.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "grafana-label-enforcer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "grafana-label-enforcer.fullname" . }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: prom-label-enforcer
        image: quay.io/prometheuscommunity/prom-label-proxy@sha256:574bc3be1e514767530d555097e2ff01a774b2c9a04b9327810619cb9cbee721
        imagePullPolicy: IfNotPresent
        resources: {{- toYaml .Values.resources | nindent 10 }}
        args:
        - "--insecure-listen-address=0.0.0.0:9090"
        - "--upstream={{ .Values.upstreamUrl }}"
        - "--label={{ .Values.enforcementLabel }}"
        - "--enable-label-apis=true"
        ports:
        - containerPort: 9090
          name: promql
