apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sc-logs-retention.fullname" . }}-env
  labels:
    {{- include "sc-logs-retention.labels" . | nindent 4 }}
data:
  AWS_DEFAULT_REGION: {{ .Values.s3.region }}
  S3_REGION_ENDPOINT: {{ .Values.s3.regionEndpoint }}
  S3_BUCKET: {{ .Values.s3.bucket }}
  RETENTION_DAYS: {{ .Values.s3.retentionDays | quote }}
