apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sc-logs-retention.fullname" . }}
  labels:
    {{- include "sc-logs-retention.labels" . | nindent 4 }}
stringData:
{{- if .Values.s3.enabled }}
  s3_access_key: "{{ .Values.s3.accessKey }}"
  s3_secret_key: "{{ .Values.s3.secretKey }}"
{{- else if .Values.gcs.enabled }}
  gcs-credentials.json: |
    {{- .Values.gcs.keyfileData | nindent 4 }}
{{- end }}
