apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sc-logs-retention.fullname" . }}
  labels:
    {{- include "sc-logs-retention.labels" . | nindent 4 }}
stringData:
  s3_access_key: "{{ .Values.s3.accessKey }}"
  s3_secret_key: "{{ .Values.s3.secretKey }}"
