---
apiVersion: batch/v1
kind: Job
metadata:
  name: rclone-restore
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: rclone
          image: elastisys/rclone-sync:1.3.0
          args:
            - sync
            - "${SOURCE}"
            - "${DESTINATION}"
            - --log-level
            - DEBUG
          volumeMounts:
            - name: rclone-config
              mountPath: /home/rclone/.config/rclone/
      volumes:
        - name: rclone-config
          secret:
            secretName: ${RCLONE_CONFIG}
