name: cache-image

on:
  push:
    branches:
      - main

jobs:
  cache-image:
    runs-on: ubuntu-latest
    steps:
      - name: build tests main container image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            CK8S_TESTS_BUILD=true
            UID=1001
            GID=121
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          target: main
          file: ./tests/Dockerfile
          load: false
          pull: false
          push: false
          tags: compliantkubernetes-apps-tests:main
      - name: build tests unit container image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            CK8S_TESTS_BUILD=true
            UID=1001
            GID=121
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          target: unit
          file: ./tests/Dockerfile
          load: false
          pull: false
          push: false
          tags: compliantkubernetes-apps-tests:unit
