name: cache-image

on:
  push:
    branches:
      - main

jobs:
  cache-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout compliantkubernetes-apps
        uses: actions/checkout@v4
      - name: setup docker with buildx
        uses: docker/setup-buildx-action@v3
      - name: build tests main container image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          target: main
          file: ./tests/Dockerfile
          load: false
          pull: false
          push: false
          provenance: false
          tags: compliantkubernetes-apps-tests:main
      - name: build tests unit container image
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          target: unit
          file: ./tests/Dockerfile
          load: false
          pull: false
          push: false
          provenance: false
          tags: compliantkubernetes-apps-tests:unit
